### 인증 코드 발행
POST http://localhost:8080/api/v1/issue/code
Content-Type: application/json

{
  "receiver_info": "gksxodnd007@naver.com",
  "type": "EMAIL"
}

### 인증 코드 검사
POST http://localhost:8080/api/v1/verify/code
Content-Type: application/json

{
  "receiver_info": "gksxodnd007@naver.com",
  "type": "EMAIL",
  "code": "5AA0B415"
}

### 회원 가입
POST http://localhost:8080/api/v1/sign-up
Content-Type: application/json
X-Register-Token: TESTTOKEN

{
  "username": "한태웅",
  "description": "망나니",
  "image_code": 1,
  "email": "gksxodnd00@naver.com",
  "password": "1234"
}

### 로그인
POST http://localhost:8080/api/v1/sign-in
Content-Type: application/json

{
  "email": "gksxodnd007@naver.com",
  "password": "1234"
}

### 룸 생성
POST http://localhost:8080/api/v1/register/room
Content-Type: application/json
X-Authorization: 76C03F7BFF07F92ED53B14BDC1C7EE0E

{
  "title": "망나니들 모임",
  "code": "dkaf931",
  "expires_date": "2020-01-01"
}

### 룸 조인
GET http://localhost:8080/api/v1/join/room
Content-Type: application/json
X-Authorization: 1C86B939487C95365498889C524593F8

{
  "title": "망나니들 모임",
  "code": "dkaf931"
}

### 룸 리스트 가져오기
GET http://localhost:8080/api/v1/room/list
Content-Type: application/json
X-Authorization: FEAA9DC8F3A7F5DFE6DEBCD3114947D6

### 방의 매칭 정보 가져오기


### 룸 정보 가져오기
GET http://localhost:8080/api/v1/room/2
X-Authorization: AF1C8FBD13559B5FFECA93BDC57749B6

### 마니또 매칭
POST http://localhost:8080/api/v1/matching
Content-Type: application/json
X-Authorization: FEAA9DC8F3A7F5DFE6DEBCD3114947D6

{
  "room_id": 2,
  "owner_id": 1,
  "type": "USER"
}